<?xml version="1.0"?>
<analyzerinfo checksum="992564733">
        <error id="arrayIndexOutOfBounds" severity="error" msg="Array &apos;array[4]&apos; accessed at index 4, which is out of bounds." verbose="Array &apos;array[4]&apos; accessed at index 4, which is out of bounds." cwe="788" hash="7033720238105620352">
            <location file0="C:\Users\Marcel\Desktop\Bachelorarbeit\SynthethicTestCases\CWE125\Example.cpp" file="C:\Users\Marcel\Desktop\Bachelorarbeit\SynthethicTestCases\CWE125\Example.cpp" line="33" column="7" info="Array index out of bounds"/>
        </error>
  <FileInfo check="ctu">
<function-call call-id="C:/Users/Marcel/Desktop/Bachelorarbeit/SynthethicTestCases/CWE125/Example.cpp:12:5" call-funcname="getValueArray" call-argnr="1" file="C:/Users/Marcel/Desktop/Bachelorarbeit/SynthethicTestCases/CWE125/Example.cpp" line="35" col="28" call-argexpr="array" call-argvaluetype="7" call-argvalue="16"/>  </FileInfo>
  <FileInfo check="CheckUnusedFunctions">
    <functiondecl functionName="getValueArray" lineNumber="12"/>
    <functiondecl functionName="main" lineNumber="25"/>
    <functioncall functionName="array"/>
    <functioncall functionName="getValueArray"/>
    <functioncall functionName="if"/>
    <functioncall functionName="index"/>
    <functioncall functionName="len"/>
  </FileInfo>
</analyzerinfo>
